package Monopoly.GameManager;

import Monopoly.Board.*;
import Monopoly.Player.Bank;
import Monopoly.SpecialCard.GiftCard;
import Monopoly.SpecialCard.MoveCard;
import Monopoly.SpecialCard.PayCard;
import Monopoly.SpecialCard.SpecialCard;

import java.util.ArrayList;
import java.util.List;

public class GameManager {

    public void initializeBoard(){
        List<PropertyField> propertyFields = new ArrayList<>();
        List<SpecialCard> specialCards = new ArrayList<>();
        Bank bank = new Bank(0,propertyFields);
        Field field1 = new Field(0);
        PropertyField field2 = new PropertyField(1,60,bank,2);
        SpecialCardField field3 = new SpecialCardField(2);
        PropertyField field4 = new PropertyField(3,60,bank,4);
        TaxField field5 = new TaxField(4,200);
        PropertyField field6 = new PropertyField(5,200,bank,0);
        PropertyField field7 = new PropertyField(6,100,bank,6);
        SpecialCardField field8 = new SpecialCardField(7);
        PropertyField field9 = new PropertyField(8,100,bank,6);
        PropertyField field10 = new PropertyField(9,120,bank,8);
        JailField field11 = new JailField(10);
        PropertyField field12 = new PropertyField(11,140,bank,10);
        PropertyField field13 = new PropertyField(12,150,bank,0);
        PropertyField field14 = new PropertyField(13,140,bank,10);
        PropertyField field15 = new PropertyField(14,160,bank,12);
        PropertyField field16 = new PropertyField(15,200,bank,0);
        PropertyField field17 = new PropertyField(16,180,bank,14);
        SpecialCardField field18 = new SpecialCardField(17);
        PropertyField field19 = new PropertyField(18,180,bank,14);
        PropertyField field20 = new PropertyField(19,200,bank,16);
        ParkingField field21 = new ParkingField(20,0);
        PropertyField field22 = new PropertyField(21,220,bank,18);
        SpecialCardField field23 = new SpecialCardField(22);
        PropertyField field24 = new PropertyField(23,220,bank,18);
        PropertyField field25 = new PropertyField(24,240,bank,20);
        PropertyField field26 = new PropertyField(25,200,bank,0);
        PropertyField field27 = new PropertyField(26,260,bank,22);
        PropertyField field28 = new PropertyField(27,260,bank,22);
        PropertyField field29 = new PropertyField(28,150,bank,0);
        PropertyField field30 = new PropertyField(29,280,bank,24);
        GoToJailField field31 = new GoToJailField(30);
        PropertyField field32 = new PropertyField(31,300,bank,26);
        PropertyField field33 = new PropertyField(32,300,bank,26);
        SpecialCardField field34 = new SpecialCardField(33);
        PropertyField field35 = new PropertyField(34,320,bank,28);
        PropertyField field36 = new PropertyField(35,200,bank,0);
        SpecialCardField field37 = new SpecialCardField(36);
        PropertyField field38 = new PropertyField(37,350,bank,35);
        TaxField field39 = new TaxField(38,100);
        PropertyField field40 = new PropertyField(39,400,bank,50);
        List<Field> fields = new ArrayList<>();
        fields.add(field1);
        fields.add(field2);
        fields.add(field3);
        fields.add(field4);
        fields.add(field5);
        fields.add(field6);
        fields.add(field7);
        fields.add(field8);
        fields.add(field9);
        fields.add(field10);
        fields.add(field11);
        fields.add(field12);
        fields.add(field13);
        fields.add(field14);
        fields.add(field15);
        fields.add(field16);
        fields.add(field17);
        fields.add(field18);
        fields.add(field19);
        fields.add(field20);
        fields.add(field21);
        fields.add(field22);
        fields.add(field23);
        fields.add(field24);
        fields.add(field25);
        fields.add(field26);
        fields.add(field27);
        fields.add(field28);
        fields.add(field29);
        fields.add(field30);
        fields.add(field31);
        fields.add(field32);
        fields.add(field33);
        fields.add(field34);
        fields.add(field35);
        fields.add(field36);
        fields.add(field37);
        fields.add(field38);
        fields.add(field39);
        fields.add(field40);
        propertyFields.add(field2);
        propertyFields.add(field4);
        propertyFields.add(field6);
        propertyFields.add(field7);
        propertyFields.add(field9);
        propertyFields.add(field10);
        propertyFields.add(field12);
        propertyFields.add(field13);
        propertyFields.add(field14);
        propertyFields.add(field15);
        propertyFields.add(field16);
        propertyFields.add(field17);
        propertyFields.add(field19);
        propertyFields.add(field20);
        propertyFields.add(field22);
        propertyFields.add(field24);
        propertyFields.add(field25);
        propertyFields.add(field26);
        propertyFields.add(field27);
        propertyFields.add(field28);
        propertyFields.add(field29);
        propertyFields.add(field30);
        propertyFields.add(field32);
        propertyFields.add(field33);
        propertyFields.add(field35);
        propertyFields.add(field36);
        propertyFields.add(field38);
        propertyFields.add(field40);

        MoveCard card1 = new MoveCard(field1);
        MoveCard card2 = new MoveCard(field6);
        MoveCard card3 = new MoveCard(field25);
        MoveCard card4 = new MoveCard(field12);
        MoveCard card5 = new MoveCard(field40);
//        MoveCard card6 = new MoveCard(field6);
//        MoveCard card7 = new MoveCard(field40);
        MoveCard card8 = new MoveCard(field13);
//        MoveCard card9 = new MoveCard(field13);
        PayCard card10 = new PayCard(50);
        PayCard card11 = new PayCard(15);
        GiftCard card12 = new GiftCard(150);
        GiftCard card13 = new GiftCard(50);

        Board.getInstance(fields,specialCards);
    }

}
